/** C curriculum grounding for the language-independent conversational Tutor. */

import type { CourseDefinition } from './course.ts'

/** Beginner C path whose lessons each introduce one new programming concept. */
export const cCourse: CourseDefinition = {
  id: 'c-foundations',
  language: 'C',
  codeFence: 'c',
  title: 'course.title',
  description: 'course.description',
  lessons: [
    {
      id: 'hello',
      title: 'lesson.entry.title', objective: 'lesson.entry.objective', explanation: 'lesson.entry.explanation',
      syntax: 'main',
      code: 'int main(void) {\n  return 0;\n}',
      practice: 'lesson.entry.practice',
    },
    {
      id: 'header',
      title: 'lesson.header.title', objective: 'lesson.header.objective', explanation: 'lesson.header.explanation',
      syntax: '#include <stdio.h>',
      code: '#include <stdio.h>\n\nint main(void) {\n  return 0;\n}',
      practice: 'lesson.header.practice',
    },
    {
      id: 'print-text',
      title: 'lesson.printText.title', objective: 'lesson.printText.objective', explanation: 'lesson.printText.explanation',
      syntax: 'printf("text");',
      code: '#include <stdio.h>\n\nint main(void) {\n  printf("Hello");\n  return 0;\n}',
      practice: 'lesson.printText.practice',
    },
    {
      id: 'newline',
      title: 'lesson.newline.title', objective: 'lesson.newline.objective', explanation: 'lesson.newline.explanation',
      syntax: 'printf("first\\nsecond\\n");',
      code: '#include <stdio.h>\n\nint main(void) {\n  printf("first\\nsecond\\n");\n  return 0;\n}',
      practice: 'lesson.newline.practice',
    },
    {
      id: 'int-variable',
      title: 'lesson.intVariable.title', objective: 'lesson.intVariable.objective', explanation: 'lesson.intVariable.explanation',
      syntax: 'int age = 18;',
      code: 'int main(void) {\n  int age = 18;\n  return 0;\n}',
      practice: 'lesson.intVariable.practice',
    },
    {
      id: 'print-int',
      title: 'lesson.printInt.title', objective: 'lesson.printInt.objective', explanation: 'lesson.printInt.explanation',
      syntax: 'printf("%d\\n", age);',
      code: '#include <stdio.h>\n\nint main(void) {\n  int age = 18;\n  printf("%d\\n", age);\n  return 0;\n}',
      practice: 'lesson.printInt.practice',
    },
    {
      id: 'arithmetic',
      title: 'lesson.arithmetic.title', objective: 'lesson.arithmetic.objective', explanation: 'lesson.arithmetic.explanation',
      syntax: 'int total = left + right;',
      code: '#include <stdio.h>\n\nint main(void) {\n  int total = 2 + 3;\n  printf("%d\\n", total);\n  return 0;\n}',
      practice: 'lesson.arithmetic.practice',
    },
    {
      id: 'reassign',
      title: 'lesson.reassign.title', objective: 'lesson.reassign.objective', explanation: 'lesson.reassign.explanation',
      syntax: 'score = 20;',
      code: '#include <stdio.h>\n\nint main(void) {\n  int score = 10;\n  score = 20;\n  printf("%d\\n", score);\n  return 0;\n}',
      practice: 'lesson.reassign.practice',
    },
    {
      id: 'comparison',
      title: 'lesson.comparison.title', objective: 'lesson.comparison.objective', explanation: 'lesson.comparison.explanation',
      syntax: 'age >= 18',
      code: '#include <stdio.h>\n\nint main(void) {\n  int age = 20;\n  int adult = age >= 18;\n  printf("%d\\n", adult);\n  return 0;\n}',
      practice: 'lesson.comparison.practice',
    },
    {
      id: 'if',
      title: 'lesson.if.title', objective: 'lesson.if.objective', explanation: 'lesson.if.explanation',
      syntax: 'if (condition) { ... }',
      code: '#include <stdio.h>\n\nint main(void) {\n  int age = 20;\n  if (age >= 18) {\n    printf("adult\\n");\n  }\n  return 0;\n}',
      practice: 'lesson.if.practice',
    },
    {
      id: 'else',
      title: 'lesson.else.title', objective: 'lesson.else.objective', explanation: 'lesson.else.explanation',
      syntax: 'if (condition) { ... } else { ... }',
      code: '#include <stdio.h>\n\nint main(void) {\n  int age = 16;\n  if (age >= 18) {\n    printf("adult\\n");\n  } else {\n    printf("minor\\n");\n  }\n  return 0;\n}',
      practice: 'lesson.else.practice',
    },
    {
      id: 'while',
      title: 'lesson.while.title', objective: 'lesson.while.objective', explanation: 'lesson.while.explanation',
      syntax: 'while (condition) { ... }',
      code: '#include <stdio.h>\n\nint main(void) {\n  int count = 1;\n  while (count <= 3) {\n    printf("%d\\n", count);\n    count = count + 1;\n  }\n  return 0;\n}',
      practice: 'lesson.while.practice',
    },
    {
      id: 'for',
      title: 'lesson.for.title', objective: 'lesson.for.objective', explanation: 'lesson.for.explanation',
      syntax: 'for (int i = 1; i <= 3; i = i + 1) { ... }',
      code: '#include <stdio.h>\n\nint main(void) {\n  for (int i = 1; i <= 3; i = i + 1) {\n    printf("%d\\n", i);\n  }\n  return 0;\n}',
      practice: 'lesson.for.practice',
    },
    {
      id: 'function',
      title: 'lesson.function.title', objective: 'lesson.function.objective', explanation: 'lesson.function.explanation',
      syntax: 'void greet(void) { ... }',
      code: '#include <stdio.h>\n\nvoid greet(void) {\n  printf("Hello\\n");\n}\n\nint main(void) {\n  greet();\n  return 0;\n}',
      practice: 'lesson.function.practice',
    },
    {
      id: 'parameter',
      title: 'lesson.parameter.title', objective: 'lesson.parameter.objective', explanation: 'lesson.parameter.explanation',
      syntax: 'void printNumber(int number) { ... }',
      code: '#include <stdio.h>\n\nvoid printNumber(int number) {\n  printf("%d\\n", number);\n}\n\nint main(void) {\n  printNumber(7);\n  return 0;\n}',
      practice: 'lesson.parameter.practice',
    },
    {
      id: 'return-value',
      title: 'lesson.returnValue.title', objective: 'lesson.returnValue.objective', explanation: 'lesson.returnValue.explanation',
      syntax: 'int doubleNumber(int number) { return number * 2; }',
      code: '#include <stdio.h>\n\nint doubleNumber(int number) {\n  return number * 2;\n}\n\nint main(void) {\n  int result = doubleNumber(4);\n  printf("%d\\n", result);\n  return 0;\n}',
      practice: 'lesson.returnValue.practice',
    },
    {
      id: 'array',
      title: 'lesson.array.title', objective: 'lesson.array.objective', explanation: 'lesson.array.explanation',
      syntax: 'int scores[3] = {88, 91, 95};',
      code: 'int main(void) {\n  int scores[3] = {88, 91, 95};\n  return 0;\n}',
      practice: 'lesson.array.practice',
    },
    {
      id: 'array-index',
      title: 'lesson.arrayIndex.title', objective: 'lesson.arrayIndex.objective', explanation: 'lesson.arrayIndex.explanation',
      syntax: 'scores[0]',
      code: '#include <stdio.h>\n\nint main(void) {\n  int scores[3] = {88, 91, 95};\n  printf("%d\\n", scores[0]);\n  return 0;\n}',
      practice: 'lesson.arrayIndex.practice',
    },
    {
      id: 'array-loop',
      title: 'lesson.arrayLoop.title', objective: 'lesson.arrayLoop.objective', explanation: 'lesson.arrayLoop.explanation',
      syntax: 'for (int i = 0; i < 3; i = i + 1) { ... }',
      code: '#include <stdio.h>\n\nint main(void) {\n  int scores[3] = {88, 91, 95};\n  for (int i = 0; i < 3; i = i + 1) {\n    printf("%d\\n", scores[i]);\n  }\n  return 0;\n}',
      practice: 'lesson.arrayLoop.practice',
    },
    {
      id: 'pointer',
      title: 'lesson.pointer.title', objective: 'lesson.pointer.objective', explanation: 'lesson.pointer.explanation',
      syntax: 'int *pointer = &value;',
      code: 'int main(void) {\n  int value = 42;\n  int *pointer = &value;\n  return 0;\n}',
      practice: 'lesson.pointer.practice',
    },
    {
      id: 'dereference-read',
      title: 'lesson.dereferenceRead.title', objective: 'lesson.dereferenceRead.objective', explanation: 'lesson.dereferenceRead.explanation',
      syntax: '*pointer',
      code: '#include <stdio.h>\n\nint main(void) {\n  int value = 42;\n  int *pointer = &value;\n  printf("%d\\n", *pointer);\n  return 0;\n}',
      practice: 'lesson.dereferenceRead.practice',
    },
    {
      id: 'dereference-write',
      title: 'lesson.dereferenceWrite.title', objective: 'lesson.dereferenceWrite.objective', explanation: 'lesson.dereferenceWrite.explanation',
      syntax: '*pointer = 7;',
      code: '#include <stdio.h>\n\nint main(void) {\n  int value = 42;\n  int *pointer = &value;\n  *pointer = 7;\n  printf("%d\\n", value);\n  return 0;\n}',
      practice: 'lesson.dereferenceWrite.practice',
    },
  ],
}
