/** C course content for the language-independent learning flow. */

import type { CourseDefinition } from './course.ts'

/** Introductory C path from program structure through pointers. */
export const cCourse: CourseDefinition = {
  id: 'c-foundations',
  title: 'course.title',
  description: 'course.description',
  lessons: [
    {
      id: 'hello',
      title: 'lesson.hello.title',
      objective: 'lesson.hello.objective',
      explanation: 'lesson.hello.explanation',
      code: '#include <stdio.h>\n\nint main(void) {\n  printf("Hello, C!\\n");\n  return 0;\n}',
      challenge: 'lesson.hello.challenge',
      options: [
        { label: 'lesson.hello.optionA' },
        { label: 'lesson.hello.optionB' },
        { label: 'lesson.hello.optionC' },
      ],
      correctOption: 1,
      correctFeedback: 'lesson.hello.correct',
      incorrectFeedback: 'lesson.hello.incorrect',
    },
    {
      id: 'values',
      title: 'lesson.values.title',
      objective: 'lesson.values.objective',
      explanation: 'lesson.values.explanation',
      code: 'int age = 18;\ndouble score = 92.5;\nchar grade = \'A\';\n\nprintf("%d %.1f %c\\n", age, score, grade);',
      challenge: 'lesson.values.challenge',
      options: [
        { label: 'lesson.values.optionA' },
        { label: 'lesson.values.optionB' },
        { label: 'lesson.values.optionC' },
      ],
      correctOption: 0,
      correctFeedback: 'lesson.values.correct',
      incorrectFeedback: 'lesson.values.incorrect',
    },
    {
      id: 'control',
      title: 'lesson.control.title',
      objective: 'lesson.control.objective',
      explanation: 'lesson.control.explanation',
      code: 'for (int i = 1; i <= 3; i++) {\n  if (i % 2 == 0) {\n    printf("even\\n");\n  } else {\n    printf("odd\\n");\n  }\n}',
      challenge: 'lesson.control.challenge',
      options: [
        { label: 'lesson.control.optionA' },
        { label: 'lesson.control.optionB' },
        { label: 'lesson.control.optionC' },
      ],
      correctOption: 2,
      correctFeedback: 'lesson.control.correct',
      incorrectFeedback: 'lesson.control.incorrect',
    },
    {
      id: 'functions',
      title: 'lesson.functions.title',
      objective: 'lesson.functions.objective',
      explanation: 'lesson.functions.explanation',
      code: 'int square(int value) {\n  return value * value;\n}\n\nint main(void) {\n  printf("%d\\n", square(6));\n  return 0;\n}',
      challenge: 'lesson.functions.challenge',
      options: [
        { label: 'lesson.functions.optionA' },
        { label: 'lesson.functions.optionB' },
        { label: 'lesson.functions.optionC' },
      ],
      correctOption: 1,
      correctFeedback: 'lesson.functions.correct',
      incorrectFeedback: 'lesson.functions.incorrect',
    },
    {
      id: 'arrays',
      title: 'lesson.arrays.title',
      objective: 'lesson.arrays.objective',
      explanation: 'lesson.arrays.explanation',
      code: 'int scores[] = {88, 91, 95};\nint total = 0;\n\nfor (int i = 0; i < 3; i++) {\n  total += scores[i];\n}\n\nprintf("%d\\n", total);',
      challenge: 'lesson.arrays.challenge',
      options: [
        { label: 'lesson.arrays.optionA' },
        { label: 'lesson.arrays.optionB' },
        { label: 'lesson.arrays.optionC' },
      ],
      correctOption: 0,
      correctFeedback: 'lesson.arrays.correct',
      incorrectFeedback: 'lesson.arrays.incorrect',
    },
    {
      id: 'pointers',
      title: 'lesson.pointers.title',
      objective: 'lesson.pointers.objective',
      explanation: 'lesson.pointers.explanation',
      code: 'int value = 42;\nint *pointer = &value;\n\nprintf("%d\\n", *pointer);\n*pointer = 7;\nprintf("%d\\n", value);',
      challenge: 'lesson.pointers.challenge',
      options: [
        { label: 'lesson.pointers.optionA' },
        { label: 'lesson.pointers.optionB' },
        { label: 'lesson.pointers.optionC' },
      ],
      correctOption: 2,
      correctFeedback: 'lesson.pointers.correct',
      incorrectFeedback: 'lesson.pointers.incorrect',
    },
  ],
}
